import { useState, useEffect, useRef } from 'react';
import Sidebar from '../components/common/Sidebar';
import Navbar from '../components/common/Navbar';
import api from '../services/api';
import { useReactToPrint } from 'react-to-print';

const DocumentPrint = ({ doc }) => (
  <div className="p-8 max-w-2xl mx-auto">
    {/* Header */}
    <div className="text-center border-b-2 border-gray-800 pb-4 mb-6">
      <h1 className="text-2xl font-bold">MizigoFlow</h1>
      <p className="text-gray-500 text-sm">Warehouse Management System</p>
      <h2 className="text-xl font-semibold mt-2 uppercase">
        {doc.document_type === 'GRN' ? 'Goods Received Note' :
         doc.document_type === 'waybill' ? 'Waybill' : 'Delivery Note'}
      </h2>
    </div>

    {/* Document Info */}
    <div className="grid grid-cols-2 gap-4 mb-6 text-sm">
      <div>
        <p className="text-gray-500">Document No.</p>
        <p className="font-semibold">MZF-{String(doc.id).padStart(5, '0')}</p>
      </div>
      <div>
        <p className="text-gray-500">Date</p>
        <p className="font-semibold">{new Date(doc.created_at).toLocaleDateString()}</p>
      </div>
      <div>
        <p className="text-gray-500">Order #</p>
        <p className="font-semibold">#{doc.order_id}</p>
      </div>
      <div>
        <p className="text-gray-500">Order Type</p>
        <p className="font-semibold capitalize">{doc.order_type}</p>
      </div>
    </div>

    {/* Vehicle & Driver Info */}
    <div className="bg-gray-50 rounded-lg p-4 mb-6 text-sm">
      <h3 className="font-semibold mb-2">Vehicle & Driver Details</h3>
      <div className="grid grid-cols-2 gap-2">
        <div><span className="text-gray-500">Plate Number: </span><span className="font-medium">{doc.plate_number}</span></div>
        <div><span className="text-gray-500">Vehicle Type: </span><span className="font-medium capitalize">{doc.vehicle_type}</span></div>
        <div><span className="text-gray-500">Driver Name: </span><span className="font-medium">{doc.driver_name}</span></div>
        <div><span className="text-gray-500">Driver Phone: </span><span className="font-medium">{doc.driver_phone}</span></div>
        <div><span className="text-gray-500">License No.: </span><span className="font-medium">{doc.license_number || '-'}</span></div>
      </div>
    </div>

    {/* Items Table */}
    <div className="mb-6">
      <h3 className="font-semibold mb-2 text-sm">Items</h3>
      <table className="w-full text-sm border border-gray-200">
        <thead>
          <tr className="bg-gray-100">
            <th className="text-left py-2 px-3 border-b border-gray-200">#</th>
            <th className="text-left py-2 px-3 border-b border-gray-200">Product</th>
            <th className="text-left py-2 px-3 border-b border-gray-200">SKU</th>
            <th className="text-left py-2 px-3 border-b border-gray-200">Expected Qty</th>
            <th className="text-left py-2 px-3 border-b border-gray-200">Actual Qty</th>
            <th className="text-left py-2 px-3 border-b border-gray-200">Unit</th>
          </tr>
        </thead>
        <tbody>
          {doc.items?.map((item, index) => (
            <tr key={item.id} className="border-b border-gray-100">
              <td className="py-2 px-3">{index + 1}</td>
              <td className="py-2 px-3">{item.product_name}</td>
              <td className="py-2 px-3">{item.sku || '-'}</td>
              <td className="py-2 px-3">{item.expected_quantity}</td>
              <td className="py-2 px-3">{item.actual_quantity || '-'}</td>
              <td className="py-2 px-3">{item.unit_of_measure}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>

    {/* Signatures */}
    <div className="grid grid-cols-2 gap-8 mt-10 text-sm">
      <div>
        <div className="border-b border-gray-400 mb-1 h-8"></div>
        <p className="text-gray-500">Prepared By</p>
        <p className="font-medium">{doc.generated_by_name}</p>
      </div>
      <div>
        <div className="border-b border-gray-400 mb-1 h-8"></div>
        <p className="text-gray-500">Received By / Driver Signature</p>
      </div>
    </div>

    <p className="text-center text-xs text-gray-400 mt-8">
      Generated by MizigoFlow — {new Date().toLocaleString()}
    </p>
  </div>
);

const Documents = () => {
  const [documents, setDocuments] = useState([]);
  const [orders, setOrders] = useState([]);
  const [loading, setLoading] = useState(true);
  const [selectedDoc, setSelectedDoc] = useState(null);
  const [showGenerate, setShowGenerate] = useState(false);
  const [generateForm, setGenerateForm] = useState({ order_id: '', document_type: 'waybill' });
  const [submitting, setSubmitting] = useState(false);
  const [message, setMessage] = useState(null);

  const printRef = useRef();

  const handlePrint = useReactToPrint({
    content: () => printRef.current,
  });

  const fetchData = async () => {
    try {
      const [docsRes, ordersRes] = await Promise.all([
        api.get('/documents'),
        api.get('/orders'),
      ]);
      setDocuments(docsRes.data);
      setOrders(ordersRes.data);
    } catch (error) {
      console.error('Documents fetch error:', error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
  }, []);

  const handleViewDocument = async (id) => {
    try {
      const res = await api.get(`/documents/${id}`);
      setSelectedDoc(res.data);
    } catch (error) {
      console.error('View document error:', error);
    }
  };

  const handleGenerate = async () => {
    if (!generateForm.order_id) {
      setMessage({ type: 'error', text: 'Please select an order' });
      return;
    }
    try {
      setSubmitting(true);
      const endpoint = generateForm.document_type === 'GRN' ? '/documents/grn' :
                       generateForm.document_type === 'waybill' ? '/documents/waybill' :
                       '/documents/delivery-note';
      await api.post(endpoint, { order_id: parseInt(generateForm.order_id) });
      setMessage({ type: 'success', text: 'Document generated successfully' });
      setShowGenerate(false);
      fetchData();
    } catch (error) {
      setMessage({ type: 'error', text: error.response?.data?.message || 'Failed to generate document' });
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="flex min-h-screen bg-gray-50">
      <Sidebar />
      <div className="flex-1 flex flex-col">
        <Navbar title="Documents" />
        <div className="p-6 space-y-6">

          {/* Message */}
          {message && (
            <div className={`px-4 py-3 rounded-lg text-sm ${message.type === 'success' ? 'bg-green-50 text-green-700 border border-green-200' : 'bg-red-50 text-red-700 border border-red-200'}`}>
              {message.text}
              <button onClick={() => setMessage(null)} className="ml-2 font-bold">×</button>
            </div>
          )}

          {/* Header */}
          <div className="flex justify-between items-center">
            <h3 className="font-semibold text-gray-800">All Documents</h3>
            <button onClick={() => setShowGenerate(true)} className="btn-primary">
              + Generate Document
            </button>
          </div>

          {/* Generate Form */}
          {showGenerate && (
            <div className="card">
              <h4 className="font-semibold text-gray-800 mb-4">Generate Document</h4>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Document Type</label>
                  <select className="input-field" value={generateForm.document_type} onChange={(e) => setGenerateForm({ ...generateForm, document_type: e.target.value })}>
                    <option value="waybill">Waybill</option>
                    <option value="GRN">Goods Received Note (GRN)</option>
                    <option value="delivery_note">Delivery Note</option>
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Order</label>
                  <select className="input-field" value={generateForm.order_id} onChange={(e) => setGenerateForm({ ...generateForm, order_id: e.target.value })}>
                    <option value="">Select order</option>
                    {orders.map((o) => (
                      <option key={o.id} value={o.id}>Order #{o.id} — {o.order_type} — {o.plate_number}</option>
                    ))}
                  </select>
                </div>
              </div>
              <div className="flex gap-3 mt-4">
                <button onClick={handleGenerate} disabled={submitting} className="btn-primary">
                  {submitting ? 'Generating...' : 'Generate'}
                </button>
                <button onClick={() => setShowGenerate(false)} className="btn-secondary">Cancel</button>
              </div>
            </div>
          )}

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {/* Documents List */}
            <div className="card">
              {loading ? (
                <p className="text-gray-400 text-sm">Loading...</p>
              ) : documents.length === 0 ? (
                <p className="text-gray-400 text-sm">No documents yet</p>
              ) : (
                <div className="space-y-3">
                  {documents.map((doc) => (
                    <div
                      key={doc.id}
                      onClick={() => handleViewDocument(doc.id)}
                      className={`flex items-center justify-between p-3 rounded-lg cursor-pointer border transition-colors ${selectedDoc?.id === doc.id ? 'border-blue-300 bg-blue-50' : 'border-gray-100 hover:bg-gray-50'}`}
                    >
                      <div>
                        <p className="text-sm font-medium text-gray-800">
                          MZF-{String(doc.id).padStart(5, '0')} — {doc.document_type === 'GRN' ? 'Goods Received Note' : doc.document_type === 'waybill' ? 'Waybill' : 'Delivery Note'}
                        </p>
                        <p className="text-xs text-gray-500">Order #{doc.order_id} · {doc.generated_by_name}</p>
                        <p className="text-xs text-gray-400">{new Date(doc.created_at).toLocaleDateString()}</p>
                      </div>
                      <span className="badge-info capitalize">{doc.document_type}</span>
                    </div>
                  ))}
                </div>
              )}
            </div>

            {/* Document Preview */}
            {selectedDoc && (
              <div className="card">
                <div className="flex justify-between items-center mb-4">
                  <h4 className="font-semibold text-gray-800">Document Preview</h4>
                  <button onClick={handlePrint} className="btn-primary text-sm">
                    🖨️ Print
                  </button>
                </div>
                <div ref={printRef}>
                  <DocumentPrint doc={selectedDoc} />
                </div>
              </div>
            )}
          </div>

        </div>
      </div>
    </div>
  );
};

export default Documents;